configurations:
  plant_associated_env_broad_scale:
    output_file_name: "voting_sheets_output/plant_associated_env_broad_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:00000428"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_broad_scale"
    nmdc_context_selector: "env_broad_scale_id"
    first_where: "lower(s1.value) like '%plant%'"
    ncbi_package_selector: "plant-associated.6.0"
    nmdc_package_selector: "plant-associated"
    CONTEXT_ENUM: "EnvBroadScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvBroadScaleSoilEnum_11_1"

  sediment_env_broad_scale:
    output_file_name: "voting_sheets_output/sediment_env_broad_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:00000428"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_broad_scale"
    nmdc_context_selector: "env_broad_scale_id"
    first_where: "lower(s1.value) like '%sediment%'"
    ncbi_package_selector: "sediment.6.0"
    nmdc_package_selector: "sediment"
    CONTEXT_ENUM: "EnvBroadScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvBroadScaleSoilEnum_11_1"

  soil_env_broad_scale:
    output_file_name: "voting_sheets_output/soil_env_broad_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:00000428"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_broad_scale"
    nmdc_context_selector: "env_broad_scale_id"
    first_where: "lower(s1.value) like '%soil%'"
    ncbi_package_selector: "soil.6.0"
    nmdc_package_selector: "soil"
    CONTEXT_ENUM: "EnvBroadScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvBroadScaleSoilEnum_10_7"

  plant_associated_env_local_scale:
    output_file_name: "voting_sheets_output/plant_associated_env_local_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:01000813"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_local_scale"
    nmdc_context_selector: "env_local_scale_id"
    first_where: "lower(s1.value) like '%plant%'"
    ncbi_package_selector: "plant-associated.6.0"
    nmdc_package_selector: "plant-associated"
    CONTEXT_ENUM: "EnvLocalScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvLocalScaleSoilEnum_11_1"

  sediment_env_local_scale:
    output_file_name: "voting_sheets_output/sediment_env_local_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:01000813"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_local_scale"
    nmdc_context_selector: "env_local_scale_id"
    first_where: "lower(s1.value) like '%sediment%'"
    ncbi_package_selector: "sediment.6.0"
    nmdc_package_selector: "sediment"
    CONTEXT_ENUM: "EnvLocalScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvLocalScaleSoilEnum_11_1"

  soil_env_local_scale:
    output_file_name: "voting_sheets_output/soil_env_local_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:01000813"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_local_scale"
    nmdc_context_selector: "env_local_scale_id"
    first_where: "lower(s1.value) like '%soil%'"
    ncbi_package_selector: "soil.6.0"
    nmdc_package_selector: "soil"
    CONTEXT_ENUM: "EnvLocalScaleSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvLocalScaleSoilEnum_10_7"

  plant_associated_env_medium:
    output_file_name: "voting_sheets_output/plant_associated_env_medium_voting_sheet.tsv"
    semantic_anchor: "ENVO:00010483"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_medium"
    nmdc_context_selector: "env_medium_id"
    first_where: "lower(s1.value) like '%plant%'"
    ncbi_package_selector: "plant-associated.6.0"
    nmdc_package_selector: "plant-associated"
    CONTEXT_ENUM: "EnvMediumSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvMediumSoilEnum_11_1"

  sediment_env_medium:
    output_file_name: "voting_sheets_output/sediment_env_medium_voting_sheet.tsv"
    semantic_anchor: "ENVO:00010483"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_medium"
    nmdc_context_selector: "env_medium_id"
    first_where: "lower(s1.value) like '%sediment%'"
    ncbi_package_selector: "sediment.6.0"
    nmdc_package_selector: "sediment"
    CONTEXT_ENUM: "EnvMediumSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/refs/tags/v11.1.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvMediumSoilEnum_11_1"

  soil_env_medium:
    output_file_name: "voting_sheets_output/soil_env_medium_voting_sheet.tsv"
    semantic_anchor: "ENVO:00010483"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_medium"
    nmdc_context_selector: "env_medium_id"
    first_where: "lower(s1.value) like '%soil%'"
    ncbi_package_selector: "soil.6.0"
    nmdc_package_selector: "soil"
    CONTEXT_ENUM: "EnvMediumSoilEnum"
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "EnvMediumSoilEnum_10_7"

  water_env_broad_scale:
    output_file_name: "voting_sheets_output/water_env_broad_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:00000428"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_broad_scale"
    nmdc_context_selector: "env_broad_scale_id"
    first_where: "lower(s1.value) like '%aquatic%' and lower(s1.value) not like '%sediment%'"
    ncbi_package_selector: "water.6.0"
    nmdc_package_selector: "water"
    CONTEXT_ENUM: ""
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "no_comparison_enum"

  water_env_local_scale:
    output_file_name: "voting_sheets_output/water_env_local_scale_voting_sheet.tsv"
    semantic_anchor: "ENVO:01000813"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_local_scale"
    nmdc_context_selector: "env_local_scale_id"
    first_where: "lower(s1.value) like '%aquatic%' and lower(s1.value) not like '%sediment%'"
    ncbi_package_selector: "water.6.0"
    nmdc_package_selector: "water"
    CONTEXT_ENUM: ""
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "no_comparison_enum"

  water_env_medium:
    output_file_name: "voting_sheets_output/water_env_medium_voting_sheet.tsv"
    semantic_anchor: "ENVO:00010483"
    gold_context_selectors:
      - "mixs:env_broad"
      - "mixs:env_local"
      - "mixs:env_medium"
    ncbi_context_selector: "env_medium"
    nmdc_context_selector: "env_medium_id"
    first_where: "lower(s1.value) like '%aquatic%' and lower(s1.value) not like '%sediment%'"
    ncbi_package_selector: "water.6.0"
    nmdc_package_selector: "water"
    CONTEXT_ENUM: ""
    previous_submission_schema_url: "https://raw.githubusercontent.com/microbiomedata/submission-schema/v10.7.0/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml"
    comparison_enum_column_name: "no_comparison_enum"
