name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    environment: release

    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - name: Install project dependencies
      run: uv sync --locked

    - name: Compute release version
      run: echo "NMDC_VERSION=$(uvx uv-dynamic-versioning)" >> "$GITHUB_ENV"

    - name: Generate project files
      run: |
        make clean schema-build
        sed -i "s/^version: .*/version: ${NMDC_VERSION}/" src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml
        make gen-project
        cp -r project src/nmdc_submission_schema

    - name: Build source and wheel archives
      run: uv build

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
