name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    environment: release

    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install project dependencies
      run: uv sync

    - name: Generate project files
      run: |
        make clean schema-build 
        uv run poetry-dynamic-versioning
        make gen-project
        cp -r project src/nmdc_submission_schema

    - name: Build source and wheel archives
      run: uv build

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
