name: Preview documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  preview-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Set up Python 3.
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          # Note: We wrap the `3.10` in quotes so the YAML parser doesn't interpret
          #       it as a float and convert it into `3.1`.
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install Python dependencies.
        run: uv sync --locked

      - name: Regenerate schema
        run: |
          make schema-build project/json/nmdc_submission_schema.json
      
      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          uv run mkdocs build -d dist
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1.8.1
        with:
          source-dir: dist/
          preview-branch: gh-pages
